site_name: Adonis Documentation
site_url: https://easternbloxxer.github.io/Adonis
repo_name: /Epix-Incorporated/Adonis
repo_url: https://github.com//Epix-Incorporated/Adonis

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: indigo
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: indigo
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search:
      separator: '[\s\-\.]'

nav:
  - Home: index.md
  - User Manual & Feature Showcase: User-Manual-&-Feature-Showcase.md
  - Guides:
    - Creating a theme: guides/creating-a-theme.md
  - Tables:
    - Shared:
      - The "Service" Metatable: tables/shared/service.md
    - Server: 
      - Admin: tables/server/admin.md
      - Anti: tables/server/anti.md
      - Commands: tables/server/commands.md
      - Core: tables/server/core.md
      - Functions: tables/server/functions.md
      - Logs: tables/server/logs.md
      - Process: tables/server/process.md
      - Remote: tables/server/remote.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences